// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: stand.proto

package stand

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Stand) Reset() {
	*x = Stand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stand) ProtoMessage() {}

func (x *Stand) ProtoReflect() protoreflect.Message {
	mi := &file_stand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stand.ProtoReflect.Descriptor instead.
func (*Stand) Descriptor() ([]byte, []int) {
	return file_stand_proto_rawDescGZIP(), []int{0}
}

func (x *Stand) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stand) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CreateStandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *CreateStandRequest) Reset() {
	*x = CreateStandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStandRequest) ProtoMessage() {}

func (x *CreateStandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStandRequest.ProtoReflect.Descriptor instead.
func (*CreateStandRequest) Descriptor() ([]byte, []int) {
	return file_stand_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStandRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type StandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stand *Stand `protobuf:"bytes,1,opt,name=stand,proto3" json:"stand,omitempty"`
}

func (x *StandResponse) Reset() {
	*x = StandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandResponse) ProtoMessage() {}

func (x *StandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandResponse.ProtoReflect.Descriptor instead.
func (*StandResponse) Descriptor() ([]byte, []int) {
	return file_stand_proto_rawDescGZIP(), []int{2}
}

func (x *StandResponse) GetStand() *Stand {
	if x != nil {
		return x.Stand
	}
	return nil
}

// Mensajes y respuestas para leer los stands
type ReadStandsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadStandsRequest) Reset() {
	*x = ReadStandsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stand_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStandsRequest) ProtoMessage() {}

func (x *ReadStandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stand_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStandsRequest.ProtoReflect.Descriptor instead.
func (*ReadStandsRequest) Descriptor() ([]byte, []int) {
	return file_stand_proto_rawDescGZIP(), []int{3}
}

type ReadStandsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stands []*Stand `protobuf:"bytes,1,rep,name=stands,proto3" json:"stands,omitempty"`
}

func (x *ReadStandsResponse) Reset() {
	*x = ReadStandsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stand_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStandsResponse) ProtoMessage() {}

func (x *ReadStandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stand_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStandsResponse.ProtoReflect.Descriptor instead.
func (*ReadStandsResponse) Descriptor() ([]byte, []int) {
	return file_stand_proto_rawDescGZIP(), []int{4}
}

func (x *ReadStandsResponse) GetStands() []*Stand {
	if x != nil {
		return x.Stands
	}
	return nil
}

var File_stand_proto protoreflect.FileDescriptor

var file_stand_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x47, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6e,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6e, 0x64,
	0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x6e, 0x64, 0x73, 0x32, 0xa1, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x6e, 0x64, 0x12, 0x1d, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49,
	0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x1c, 0x2e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x73, 0x6d, 0x61, 0x65, 0x6c, 0x4e, 0x69,
	0x63, 0x6f, 0x6c, 0x61, 0x73, 0x2f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_stand_proto_rawDescOnce sync.Once
	file_stand_proto_rawDescData = file_stand_proto_rawDesc
)

func file_stand_proto_rawDescGZIP() []byte {
	file_stand_proto_rawDescOnce.Do(func() {
		file_stand_proto_rawDescData = protoimpl.X.CompressGZIP(file_stand_proto_rawDescData)
	})
	return file_stand_proto_rawDescData
}

var file_stand_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stand_proto_goTypes = []interface{}{
	(*Stand)(nil),              // 0: inventory.Stand
	(*CreateStandRequest)(nil), // 1: inventory.CreateStandRequest
	(*StandResponse)(nil),      // 2: inventory.StandResponse
	(*ReadStandsRequest)(nil),  // 3: inventory.ReadStandsRequest
	(*ReadStandsResponse)(nil), // 4: inventory.ReadStandsResponse
}
var file_stand_proto_depIdxs = []int32{
	0, // 0: inventory.StandResponse.stand:type_name -> inventory.Stand
	0, // 1: inventory.ReadStandsResponse.stands:type_name -> inventory.Stand
	1, // 2: inventory.StandService.CreateStand:input_type -> inventory.CreateStandRequest
	3, // 3: inventory.StandService.ReadStands:input_type -> inventory.ReadStandsRequest
	2, // 4: inventory.StandService.CreateStand:output_type -> inventory.StandResponse
	4, // 5: inventory.StandService.ReadStands:output_type -> inventory.ReadStandsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stand_proto_init() }
func file_stand_proto_init() {
	if File_stand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stand_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStandsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stand_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStandsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stand_proto_goTypes,
		DependencyIndexes: file_stand_proto_depIdxs,
		MessageInfos:      file_stand_proto_msgTypes,
	}.Build()
	File_stand_proto = out.File
	file_stand_proto_rawDesc = nil
	file_stand_proto_goTypes = nil
	file_stand_proto_depIdxs = nil
}
